name: 'goreleaser-npm-publisher'
description: 'Build and publish npm packages based on goreleaser output folder'
author: 'Evgeny Abramovich'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'package'
  color: 'red'

# Define your inputs here.
inputs:
  project:
    description: 'Path to the project with was built by GoReleaser'
    required: true
    default: '.'
  builder:
    description: 'Name of the builder'
    required: true
  prefix:
    description: 'Prefix for the npm package'
  description:
    description: 'Description of the npm package'

runs:
  using: node20
  main: dist/index.js
