name: 'The name of your action here'
description: 'Provide a description here'
author: 'Evgeny Abramovich'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'package'
  color: 'yellow'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
